<?php

namespace Database\Seeders;

use App\Models\IbuHamil;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class IbuHamilSeeder extends Seeder
{
    public function run(): void
    {
        $samples = [
            [
                'kode_ibu_hamil' => 'P-2023-014',
                'nama' => 'Ibu Hamil 1',
                'tanggal_lahir' => Carbon::now()->subYears(36)->format('Y-01-01'),
                'nomor_telepon' => '0812345678910',
                'desa_kelurahan' => 'Taman Sari',
                'hpht' => '2025-04-04',
                'hpl' => '2026-01-11',
                'usia_kehamilan_minggu' => 8,
                'status_kehamilan' => 'Trimester I',
                'status_anemia' => 'Sedang (7 - 9,9)',
                'kadar_hb' => 8.5,
                'imt' => 24.13,
                'lila' => 23.0,
                'berat_badan_sebelum_hamil' => 55.0,
                'tinggi_badan' => 151.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-015',
                'nama' => 'Ibu Hamil 2',
                'tanggal_lahir' => Carbon::now()->subYears(25)->format('Y-03-15'),
                'nomor_telepon' => '0812345678911',
                'desa_kelurahan' => 'Maphar',
                'hpht' => '2025-04-04',
                'hpl' => '2026-01-11',
                'usia_kehamilan_minggu' => 8,
                'status_kehamilan' => 'Trimester I',
                'status_anemia' => 'Sedang (7 - 9,9)',
                'kadar_hb' => 8.8,
                'imt' => 16.94,
                'lila' => 21.8,
                'berat_badan_sebelum_hamil' => 41.0,
                'tinggi_badan' => 155.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-016',
                'nama' => 'Ibu Hamil 3',
                'tanggal_lahir' => Carbon::now()->subYears(28)->format('Y-05-20'),
                'nomor_telepon' => '0812345678912',
                'desa_kelurahan' => 'Tangki',
                'hpht' => '2025-04-04',
                'hpl' => '2026-01-11',
                'usia_kehamilan_minggu' => 8,
                'status_kehamilan' => 'Trimester I',
                'status_anemia' => 'Sedang (7 - 9,9)',
                'kadar_hb' => 9.2,
                'imt' => 18.20,
                'lila' => 22.0,
                'berat_badan_sebelum_hamil' => 45.0,
                'tinggi_badan' => 157.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-017',
                'nama' => 'Ibu Hamil 4',
                'tanggal_lahir' => Carbon::now()->subYears(32)->format('Y-07-12'),
                'nomor_telepon' => '0812345678913',
                'desa_kelurahan' => 'Taman Sari',
                'hpht' => '2025-04-04',
                'hpl' => '2026-01-11',
                'usia_kehamilan_minggu' => 8,
                'status_kehamilan' => 'Trimester I',
                'status_anemia' => 'Ringan (10 - 10,9)',
                'kadar_hb' => 10.4,
                'imt' => 16.89,
                'lila' => 21.9,
                'berat_badan_sebelum_hamil' => 42.0,
                'tinggi_badan' => 158.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-018',
                'nama' => 'Ibu Hamil 5',
                'tanggal_lahir' => Carbon::now()->subYears(20)->format('Y-09-08'),
                'nomor_telepon' => '0812345678914',
                'desa_kelurahan' => 'Mangga Besar',
                'hpht' => '2025-04-04',
                'hpl' => '2026-01-11',
                'usia_kehamilan_minggu' => 8,
                'status_kehamilan' => 'Trimester I',
                'status_anemia' => 'Normal (≥ 11)',
                'kadar_hb' => 11.5,
                'imt' => 20.15,
                'lila' => 21.0,
                'berat_badan_sebelum_hamil' => 48.0,
                'tinggi_badan' => 154.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-019',
                'nama' => 'Ibu Hamil 6',
                'tanggal_lahir' => Carbon::now()->subYears(37)->format('Y-11-23'),
                'nomor_telepon' => '0812345678915',
                'desa_kelurahan' => 'Keagungan',
                'hpht' => '2025-03-01',
                'hpl' => '2025-12-08',
                'usia_kehamilan_minggu' => 13,
                'status_kehamilan' => 'Trimester II',
                'status_anemia' => 'Berat (< 7)',
                'kadar_hb' => 6.5,
                'imt' => 31.2,
                'lila' => 20.5,
                'berat_badan_sebelum_hamil' => 75.0,
                'tinggi_badan' => 155.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-020',
                'nama' => 'Ibu Hamil 7',
                'tanggal_lahir' => Carbon::now()->subYears(23)->format('Y-02-14'),
                'nomor_telepon' => '0812345678916',
                'desa_kelurahan' => 'Glodok',
                'hpht' => '2025-03-10',
                'hpl' => '2025-12-17',
                'usia_kehamilan_minggu' => 12,
                'status_kehamilan' => 'Trimester I',
                'status_anemia' => 'Normal (≥ 11)',
                'kadar_hb' => 12.1,
                'imt' => 22.4,
                'lila' => 24.5,
                'berat_badan_sebelum_hamil' => 52.0,
                'tinggi_badan' => 152.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-021',
                'nama' => 'Ibu Hamil 8',
                'tanggal_lahir' => Carbon::now()->subYears(29)->format('Y-06-30'),
                'nomor_telepon' => '0812345678917',
                'desa_kelurahan' => 'Pinangsia',
                'hpht' => '2025-02-15',
                'hpl' => '2025-11-22',
                'usia_kehamilan_minggu' => 15,
                'status_kehamilan' => 'Trimester II',
                'status_anemia' => 'Ringan (10 - 10,9)',
                'kadar_hb' => 10.1,
                'imt' => 26.5,
                'lila' => 25.0,
                'berat_badan_sebelum_hamil' => 63.0,
                'tinggi_badan' => 154.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-022',
                'nama' => 'Ibu Hamil 9',
                'tanggal_lahir' => Carbon::now()->subYears(18)->format('Y-08-19'),
                'nomor_telepon' => '0812345678918',
                'desa_kelurahan' => 'Krukut',
                'hpht' => '2025-04-10',
                'hpl' => '2026-01-17',
                'usia_kehamilan_minggu' => 7,
                'status_kehamilan' => 'Trimester I',
                'status_anemia' => 'Sedang (7 - 9,9)',
                'kadar_hb' => 8.0,
                'imt' => 17.5,
                'lila' => 21.5,
                'berat_badan_sebelum_hamil' => 39.0,
                'tinggi_badan' => 150.0,
            ],
            [
                'kode_ibu_hamil' => 'P-2023-023',
                'nama' => 'Ibu Hamil 10',
                'tanggal_lahir' => Carbon::now()->subYears(30)->format('Y-10-05'),
                'nomor_telepon' => '0812345678919',
                'desa_kelurahan' => 'Taman Sari',
                'hpht' => '2025-01-15',
                'hpl' => '2025-10-22',
                'usia_kehamilan_minggu' => 20,
                'status_kehamilan' => 'Trimester II',
                'status_anemia' => 'Normal (≥ 11)',
                'kadar_hb' => 11.8,
                'imt' => 23.1,
                'lila' => 24.0,
                'berat_badan_sebelum_hamil' => 56.0,
                'tinggi_badan' => 156.0,
            ],
        ];

        foreach ($samples as $sample) {
            IbuHamil::updateOrCreate(['kode_ibu_hamil' => $sample['kode_ibu_hamil']], $sample);
        }
    }
}
